export const Paths = {
  home: 'home',
  login: 'login',
  register: 'register',
  user: 'me',
  trips: 'trips',
  tripsDetail: 'trips/:id',
  tripPlan: 'tripPlan',
  buildTrip: 'BuildTrip',
  buildTripById: 'BuildTrip/:tripId',
  routes: 'routes',
  routeDetail: 'routes/:id',
  places: 'places',
  placeDetail: 'places/:id',
  planningResultPage: 'planningResultPage',
  about: 'about',
  contact: 'contact',
  admin: 'admin',
  adminDashboard: 'dashboard',
  adminTrips: 'trips',
  adminTripsPending: 'trips/pending',
  adminPlaces: 'places',
  adminUsers: 'users',
};
